repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py311-plus"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        name: bandit (medium/high gate)
        args:
          - "-r"
          - "src"
          - "scripts"
          - "-f"
          - "json"
          - "-q"
          - "-c"
          - ".bandit"
