FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y     fonts-farsiweb     && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-advanced.txt .
RUN pip install --no-cache-dir -r requirements-advanced.txt

RUN mkdir -p /app/test-results

COPY . .

RUN mkdir -p /root/.config/matplotlib
COPY assets/fonts/matplotlibrc /root/.config/matplotlib/matplotlibrc

CMD ["pytest"]
