groups:
  - name: critical_alerts
    rules:
      - alert: AllocationFailuresHigh
        expr: (sum by () (rate(allocation_failed_total[10m])) / (sum by () (rate(allocation_success_total[10m])) + sum by () (rate(allocation_failed_total[10m])))) > 0.05
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: "Allocation failures > 5%"
      - alert: ResponseTimeHigh
        expr: histogram_quantile(0.95, sum by (le) (rate(allocation_duration_seconds_bucket[10m]))) > 10
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Allocation P95 > 10s"
      - alert: DBConnectionFailures
        expr: rate(db_query_duration_seconds_count[5m]) == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "No DB queries observed; possible outage"
