database:
  url: ${DATABASE_URL}
redis:
  url: ${REDIS_URL}
performance:
  workers: 8
  batch_size: 1000
security:
  jwt_required: true
  rate_limit_per_min: 300
monitoring:
  metrics: true
  log_level: INFO
backup:
  schedule: nightly
