"""Generate the WinSW XML manifest for the Student Mentor service."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from textwrap import dedent

from src.reliability.atomic import atomic_write_text

DEFAULT_VERSION = "3.0.2"
DEFAULT_PORT = 18000
TARGET_PATH = Path("windows_service/StudentMentorService.xml")

_TEMPLATE = dedent(
    """\
    <?xml version="1.0" encoding="utf-8"?>
    <!-- Generated by tools/generate_winsw.py; version={version} -->
    <service>
      <id>StudentMentorService</id>
      <name>Student Mentor Allocation Service</name>
      <description>FastAPI backend for ImportToSabt exports (WinSW managed).</description>
      <executable>python</executable>
      <arguments>{arguments}</arguments>
      <workingdirectory>%BASE%</workingdirectory>
      <stoptimeout>15</stoptimeout>
      <startmode>Automatic</startmode>
      <logpath>{log_path}</logpath>
      <log mode="roll-by-size">
        <sizeThreshold>5242880</sizeThreshold>
        <keepFiles>5</keepFiles>
      </log>
      <env name="PYTHONUTF8" value="1"/>
      <env name="PYTHONUNBUFFERED" value="1"/>
      <env name="FAKE_WEBVIEW" value="0"/>
      <restart mode="delayed" period="5 sec" reset="1 hour"/>
      <download url="https://github.com/winsw/winsw/releases/download/v{version}/WinSW-x64.exe"/>
    </service>
    """
)


def _environment_port_default() -> int:
    raw = os.getenv("STUDENT_MENTOR_APP_PORT")
    if raw is None:
        return DEFAULT_PORT
    try:
        return int(raw)
    except ValueError:
        return DEFAULT_PORT


def render(version: str = DEFAULT_VERSION, *, port: int = DEFAULT_PORT) -> str:
    log_path = "%APPDATA%\\StudentMentorApp\\logs"
    arguments = f"-m windows_service.controller run --port {port}"
    return _TEMPLATE.format(version=version, log_path=log_path, arguments=arguments)


def generate(path: Path = TARGET_PATH, *, version: str = DEFAULT_VERSION, port: int = DEFAULT_PORT) -> Path:
    payload = render(version, port=port)
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(path, payload)
    return path


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate WinSW XML manifest.")
    parser.add_argument("--version", default=DEFAULT_VERSION, help="WinSW release version.")
    parser.add_argument("--output", default=str(TARGET_PATH), help="Destination XML path.")
    parser.add_argument("--port", type=int, default=None, help="Fixed port for the backend service.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    port = args.port if args.port is not None else _environment_port_default()
    target = generate(Path(args.output), version=args.version, port=port)
    message = f"Generated {target} for WinSW {args.version}"
    message += f" (port={port})"
    print(message)  # noqa: T201 - intentional CLI output
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
