name: API Hardening

on:
  pull_request:
    paths:
      - 'src/api/**'
      - 'tests/**'
      - 'tools/**'
      - 'docs/**'
      - 'migrations/**'
      - '.github/workflows/api-hardening.yml'
  push:
    branches: [main]
    paths:
      - 'src/api/**'
      - 'tests/**'
      - 'tools/**'
      - 'docs/**'
      - 'migrations/**'
      - '.github/workflows/api-hardening.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'
      REDIS_URL: redis://localhost:6379/15
      PYTEST_REDIS: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt redis>=5 openpyxl>=3.1

      - name: Run targeted pytest suite
        run: |
          pytest -q -k "excel or admin or metrics_auth or shared_backend or latency_budget or hardened_api"

      - name: Run full pytest smoke (nightly)
        if: github.event_name == 'schedule'
        run: pytest -q

      - name: Static analysis
        run: |
          ruff check .
          mypy --config-file mypy.ini
