name: CI (minimal)

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tehran
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONWARNINGS: error
      STRICT_CI_REDIS_URL: redis://localhost:6379/0
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip (quick)
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          # پوشش ماژول‌های تستی رایج
          python -m pip install redis prometheus_client

      - name: Redis readiness (short backoff)
        run: |
          python - <<'PY'
          import os, time, hashlib
          try:
              import redis
          except ImportError:
              raise SystemExit(0)
          url = os.environ.get("STRICT_CI_REDIS_URL")
          if not url: raise SystemExit(0)
          base, attempts = 0.4, 5
          for i in range(1, attempts+1):
              try:
                  c = redis.Redis.from_url(url, socket_timeout=1.5)
                  c.ping(); c.close(); break
              except Exception as e:
                  if i==attempts: raise
                  j = int(hashlib.blake2b(f"min-ci::{i}".encode(), digest_size=4).hexdigest(),16)%400/1000
                  time.sleep(base*(2**(i-1))+j)
          PY

      - name: Pre-test Redis flush (if available)
        run: |
          python - <<'PY'
          import os, sys
          try:
              import redis
          except ImportError:
              sys.exit(0)
          url = os.environ.get("STRICT_CI_REDIS_URL")
          if not url: sys.exit(0)
          r = redis.from_url(url, socket_connect_timeout=2, socket_timeout=3)
          try:
              r.flushall()
          finally:
              r.close()
          PY

      - name: Run tests
        run: pytest -q -W error
