name: Lint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  PIP_NO_CACHE_DIR: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ruff
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir ruff

      - name: Run ruff check
        run: ruff check . --output-format=github

      - name: Run ruff format
        run: ruff format --check .

  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir mypy types-PyYAML

      - name: Run mypy
        run: mypy src
