name: Quality Gates

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    env:
      TZ: Asia/Tehran
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONWARNINGS: error

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Cache Ruff
        uses: actions/cache@v4
        with:
          path: ~/.cache/ruff
          key: ruff-${{ hashFiles('**/pyproject.toml') }}-${{ matrix.python-version }}

      - name: Cache Mypy
        uses: actions/cache@v4
        with:
          path: ~/.cache/mypy
          key: mypy-${{ hashFiles('**/pyproject.toml') }}-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,ci]

      - name: Ruff lint
        run: |
          # استفاده از پیکربندی پروژه
          python -m ruff check .

      - name: Mypy strict
        run: |
          python -m mypy --config-file pyproject.toml .

      - name: Pydocstyle
        run: |
          # استفاده از پیکربندی پروژه
          python -m pydocstyle .

      - name: UTF-8 BOM guard
        run: |
          python tools/bom_guard.py --json

      - name: Run quality tests
        run: |
          pytest -q -W error tests/ci -k "quality"

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e .[security]

      - name: Run security tests
        run: |
          pytest -q -W error tests/security tests/export/test_xlsx_excel_safety.py

  performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e .[perf]

      - name: Run performance tests
        run: |
          pytest -q -W error tests/perf
