name: Quality Gates

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tehran
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTHONWARNINGS: error
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip (quick)
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          # تضمین نصب ابزارهای کیفی حتی اگر در extras نباشند
          python -m pip install ruff mypy pydocstyle

      - name: Ruff lint
        run: >-
          python -m ruff check
          tools/bom_guard.py
          tools/strip_bom.py
          tests/ci/conftest.py
          tests/ci/test_bom_guard.py
          tests/ci/test_ruff_gate.py
          tests/ci/test_mypy_strict.py
          tests/ci/test_pydocstyle_gate.py
          tests/export/test_xlsx_excel_safety.py
          tests/export/test_atomic_finalize.py
          tests/security/test_metrics_protection_all_apps.py
          tests/mw/test_middleware_order_all_apps.py
          tests/perf/test_perf_gates.py

      - name: Mypy strict
        run: python -m mypy --config-file pyproject.toml

      - name: Pydocstyle
        run: >-
          python -m pydocstyle
          tools/bom_guard.py
          tools/strip_bom.py
          tests/ci/conftest.py
          tests/ci/test_bom_guard.py
          tests/ci/test_ruff_gate.py
          tests/ci/test_mypy_strict.py
          tests/ci/test_pydocstyle_gate.py
          tests/export/test_xlsx_excel_safety.py
          tests/export/test_atomic_finalize.py
          tests/security/test_metrics_protection_all_apps.py
          tests/mw/test_middleware_order_all_apps.py
          tests/perf/test_perf_gates.py

      - name: UTF-8 BOM guard
        run: python tools/bom_guard.py --json

      - name: CI tests (quality subset)
        run: pytest -q -W error tests/ci
