name: Quality Gates

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    # ... (همان job کیفیت قبلی)

  performance:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,ci]

      - name: Debug information
        run: |
          echo "=== Environment Info ==="
          which python
          python --version
          pip list | grep -E "(pytest|student-mentor)"
          echo "=== Test Discovery ==="
          python -m pytest tests/perf/ --collect-only -q

      - name: Run performance tests
        run: |
          echo "=== Starting Performance Tests ==="
          python -m pytest -v tests/perf/ --durations=0
