name: Quality Gates

on:
  pull_request:
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      TZ: Asia/Tehran
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev,test]

      - name: Ruff lint
        run: >-
          python -m ruff check \
            tools/bom_guard.py \
            tools/strip_bom.py \
            tests/ci/conftest.py \
            tests/ci/test_bom_guard.py \
            tests/ci/test_ruff_gate.py \
            tests/ci/test_mypy_strict.py \
            tests/ci/test_pydocstyle_gate.py \
            tests/export/test_xlsx_excel_safety.py \
            tests/export/test_atomic_finalize.py \
            tests/security/test_metrics_protection_all_apps.py \
            tests/mw/test_middleware_order_all_apps.py \
            tests/perf/test_perf_gates.py

      - name: Mypy strict
        run: python -m mypy --config-file pyproject.toml

      - name: Pydocstyle
        run: >-
          python -m pydocstyle \
            tools/bom_guard.py \
            tools/strip_bom.py \
            tests/ci/conftest.py \
            tests/ci/test_bom_guard.py \
            tests/ci/test_ruff_gate.py \
            tests/ci/test_mypy_strict.py \
            tests/ci/test_pydocstyle_gate.py \
            tests/export/test_xlsx_excel_safety.py \
            tests/export/test_atomic_finalize.py \
            tests/security/test_metrics_protection_all_apps.py \
            tests/mw/test_middleware_order_all_apps.py \
            tests/perf/test_perf_gates.py

      - name: UTF-8 BOM guard
        run: python tools/bom_guard.py --json

      - name: CI tests
        run: pytest -q -W error tests/ci
