name: windows-launcher

on:
  push:
    paths:
      - 'windows_launcher/**'
      - 'windows_service/**'
      - 'tools/generate_winsw.py'
      - 'tools/fetch_winsw.ps1'
      - '.github/workflows/windows-launcher.yml'
  pull_request:
    paths:
      - 'windows_launcher/**'
      - 'windows_service/**'
      - 'tools/generate_winsw.py'
      - 'tools/fetch_winsw.ps1'
  workflow_dispatch:

env:
  PYTHONUTF8: "1"
  PYTHONWARNINGS: "error"
  PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
  PYTHONHASHSEED: "0"
  TZ: "Asia/Tehran"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          cache: 'pip'
          cache-dependency-path: |
            **/constraints*.txt
            **/requirements*.in
            **/requirements*.txt
            **/pyproject.toml

      - name: Show Python version
        run: python --version

      - name: Install (constraints-aware, retry)
        env:
          CI_CORRELATION_ID: ${{ github.run_id }}-${{ github.run_attempt }}
          PIP_REQUIRE_HASHES: ''
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          python -m pip install -U pip wheel
          python -m scripts.ci.bootstrap_guard --root . --constraints constraints-dev.txt
          python -m scripts.deps.ensure_lock --root . install --attempts 3
          python -m scripts.deps.ensure_lock --root . verify
          python -m pip install -c constraints-dev.txt pyinstaller==6.11.0
          python -m pip check
          python -m pip list --format=json > artifacts-pip-list.json

      - name: Preflight (pytest ready)
        run: |
          python -m scripts.ci.ensure_ci_ready --root . --require pytest --require pytest_asyncio --persian

      - name: Verify AGENTS spec tokens
        run: python scripts/verify_agents.py

      - name: Guard PYTHONPATH front-loading
        run: python scripts/guard_pythonpath.py

      - name: Middleware order guard
        run: python -m pytest tests/api/test_middleware_order.py -q -p pytest_asyncio

      - name: Shadowing guard tests
        run: python -m pytest tests/imports -q -p pytest_asyncio

      - name: Windows-focused tests (deterministic scope)
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          $targets = @(
            'tests/windows',
            'tests/meta/test_agents_guard.py',
            'tests/mw/test_order_from_launcher.py',
            'tests/exports/test_excel_safety_from_launcher.py',
            'tests/exports/test_atomic_finalize_from_launcher.py',
            'tests/exports/test_large_stream_from_launcher.py',
            'tests/obs/test_metrics_guard_from_launcher.py'
          )
          $common = @(
            '--rootdir', $PWD,
            '--tb=short','--strict-config','--strict-markers',
            '--ignore-glob=**/System Volume Information',
            '--ignore-glob=**/WindowsApps',
            '--ignore-glob=**/Program Files*'
          )
          python -m pytest -q $common $targets

      - name: Build launcher (PyInstaller)
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          pyinstaller windows_launcher/specs/pyinstaller.spec --clean --distpath dist --workpath build/launcher

      - name: Fetch WinSW
        run: |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          ./tools/fetch_winsw.ps1 -Destination windows_service/StudentMentorService.exe

      - name: Generate WinSW XML
        run: python tools/generate_winsw.py --output windows_service/StudentMentorService.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-launcher-${{ github.run_id }}-${{ github.run_attempt }}
          if-no-files-found: error
          path: |
            dist/**
            windows_service/StudentMentorService.xml
            windows_service/StudentMentorService.exe
            artifacts-pip-list.json
