name: windows-launcher

on:
  push:
    paths:
      - 'windows_launcher/**'
      - 'windows_service/**'
      - 'tools/generate_winsw.py'
      - 'tools/fetch_winsw.ps1'
      - '.github/workflows/windows-launcher.yml'
  pull_request:
    paths:
      - 'windows_launcher/**'
      - 'windows_service/**'
      - 'tools/generate_winsw.py'
      - 'tools/fetch_winsw.ps1'

jobs:
  build:
    runs-on: windows-2022
    env:
      PYTHONUTF8: "1"
      PYTHONWARNINGS: "error"
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      FAKE_WEBVIEW: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
          pip install pyinstaller

      - name: Run Windows-focused tests
        run: |
          pytest -q \
            tests/windows \
            tests/meta/test_agents_guard.py \
            tests/mw/test_order_from_launcher.py \
            tests/exports/test_excel_safety_from_launcher.py \
            tests/exports/test_atomic_finalize_from_launcher.py \
            tests/exports/test_large_stream_from_launcher.py \
            tests/obs/test_metrics_guard_from_launcher.py

      - name: Build launcher artifact
        run: |
          pyinstaller windows_launcher/specs/pyinstaller.spec --clean --distpath dist --workpath build/launcher

      - name: Fetch WinSW executable
        shell: pwsh
        run: ./tools/fetch_winsw.ps1 -Destination windows_service/StudentMentorService.exe

      - name: Generate WinSW XML manifest
        run: python tools/generate_winsw.py --output windows_service/StudentMentorService.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-launcher-artifacts
          if-no-files-found: error
          path: |
            dist/StudentMentorApp
            windows_service/StudentMentorService.xml
            windows_service/StudentMentorService.exe
